const $=s=>document.querySelector(s);let S,H=[],CP=JSON.parse(localStorage.cp||'{}'),best=+localStorage.best||0;
const emp=b=>{let a=[];for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(!b[r][c])a.push([r,c]);return a},cl=x=>JSON.parse(JSON.stringify(x));
function rr(s){s.x=(Math.imul(1664525,s.x)+1013904223)>>>0;return s.x/4294967296}function spawn(s){let e=emp(s.b);if(!e.length)return;let p=e[Math.floor(rr(s.rng)*e.length)];s.b[p[0]][p[1]]=rr(s.rng)<.9?2:4}
function fresh(){let s={b:Array.from({length:4},()=>Array(4).fill(0)),score:0,moves:0,start:Date.now(),rng:{x:(Date.now()^Math.random()*2**32)>>>0},marks:{}};spawn(s);spawn(s);return s}
function ln(a){a=a.filter(Boolean);let o=[],g=0;for(let i=0;i<a.length;i++){if(a[i]==a[i+1]){o.push(a[i]*2);g+=a[i]*2;i++}else o.push(a[i])}while(o.length<4)o.push(0);return[o,g]}
function mv(s,d,sp=true){let n=cl(s),b=Array.from({length:4},()=>Array(4).fill(0)),g=0;for(let i=0;i<4;i++){let a=[];for(let j=0;j<4;j++){let r=d=='L'||d=='R'?i:(d=='U'?j:3-j),c=d=='U'||d=='D'?i:(d=='L'?j:3-j);a.push(s.b[r][c])}let z=ln(a);g+=z[1];for(let j=0;j<4;j++){let r=d=='L'||d=='R'?i:(d=='U'?j:3-j),c=d=='U'||d=='D'?i:(d=='L'?j:3-j);b[r][c]=z[0][j]}}if(JSON.stringify(b)==JSON.stringify(s.b))return null;n.b=b;n.score+=g;n.moves++;if(sp)spawn(n);return n}
function mark(){let m=Math.max(...S.b.flat());for(let p=128;p<=m;p*=2)if(!S.marks[p]){S.marks[p]={t:Date.now()-S.start,m:S.moves};CP[p]=cl(S);localStorage.cp=JSON.stringify(CP)}}
function go(d){let n=mv(S,d);if(!n)return;H.push(cl(S));S=n;mark();render()}function undo(n){while(n--&&H.length)S=H.pop();render()}function newGame(){S=fresh();H=[];render()}window.undo=undo;window.newGame=newGame;
function fmt(x){let s=x/1000|0;return String(s/60|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function next(){let mode=$('#preview').value;if(mode=='off')return'';if(mode=='value'){let q=cl(S.rng);return'Kommender Wert: '+(rr(q)<.9?2:4)}let out=[],sym={L:'←',R:'→',U:'↑',D:'↓'};for(let d of ['L','R','U','D']){let n=mv(S,d,false);if(!n)continue;let e=emp(n.b),q=cl(n.rng),p=e[Math.floor(rr(q)*e.length)],v=rr(q)<.9?2:4;out.push(`${sym[d]} ${v} @ ${String.fromCharCode(65+p[1])}${p[0]+1}`)}return out.join(' · ')}
function render(){let B=$('#board');B.innerHTML='';S.b.flat().forEach(v=>{let x=document.createElement('div');x.className='t '+(v>=128?'hi':'v'+v);x.textContent=v||'';B.appendChild(x)});$('#score').textContent=S.score;best=Math.max(best,S.score);localStorage.best=best;$('#best').textContent=best;$('#moves').textContent=S.moves;$('#free').textContent=emp(S.b).length;$('#max').textContent=Math.max(...S.b.flat());$('#next').textContent=next();let a=Object.entries(S.marks);$('#marks').innerHTML=a.length?a.map(([k,v])=>`<div class=r><b>${k}</b><span>${fmt(v.t)} · Zug ${v.m}</span></div>`).join(''):'Noch keine.';let c=Object.keys(CP).map(Number).sort((a,b)=>a-b);$('#cps').innerHTML=c.length?c.map(k=>`<div class=r><b>${k}</b><button onclick=startCP(${k})>Ab hier</button></div>`).join(''):'Noch keine.'}
window.startCP=k=>{S=cl(CP[k]);S.start=Date.now();S.moves=0;S.score=0;S.marks={};H=[];render()};$('#preview').onchange=render;
let x,y,B=$('#board');B.ontouchstart=e=>{x=e.touches[0].clientX;y=e.touches[0].clientY};B.ontouchend=e=>{let X=e.changedTouches[0].clientX-x,Y=e.changedTouches[0].clientY-y;if(Math.max(Math.abs(X),Math.abs(Y))<25)return;go(Math.abs(X)>Math.abs(Y)?(X>0?'R':'L'):(Y>0?'D':'U'))};addEventListener('keydown',e=>{let d={ArrowLeft:'L',ArrowRight:'R',ArrowUp:'U',ArrowDown:'D'}[e.key];if(d)go(d)});S=fresh();render();setInterval(()=>$('#time').textContent=fmt(Date.now()-S.start),1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');