const $=s=>document.querySelector(s),K="2048pp03_";let id=0,lock=0,H=[],S;
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(K+k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(K+k,JSON.stringify(v));
let CP=load("cp",{}),RUNS=load("runs",[]),REC=load("records",{bestScore:0,bestTile:0,fastest:{},fewest:{}});
const clone=x=>JSON.parse(JSON.stringify(x));function rnd(s){s.x=(Math.imul(1664525,s.x)+1013904223)>>>0;return s.x/4294967296}
function blank(){return Array.from({length:4},()=>Array.from({length:4},()=>({v:0,id:0})))}function empty(b){let a=[];for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(!b[r][c].v)a.push([r,c]);return a}
function spawn(s){let e=empty(s.b);if(!e.length)return;let p=e[Math.floor(rnd(s.rng)*e.length)];s.b[p[0]][p[1]]={v:rnd(s.rng)<.9?2:4,id:++id}}
function fresh(startTile=2){let s={b:blank(),score:0,moves:0,start:Date.now(),startTile,marks:{},rng:{x:(Date.now()^Math.random()*4294967296)>>>0}};spawn(s);spawn(s);return s}
function move(s,d){let n=clone(s),b=blank(),gain=0,anim=[];for(let i=0;i<4;i++){let a=[];for(let j=0;j<4;j++){let r=d=="L"||d=="R"?i:(d=="U"?j:3-j),c=d=="U"||d=="D"?i:(d=="L"?j:3-j),q=s.b[r][c];if(q.v)a.push({v:q.v,id:q.id,fr:r,fc:c})}let z=[];for(let k=0;k<a.length;k++){if(a[k+1]&&a[k].v==a[k+1].v){z.push({v:a[k].v*2,id:a[k].id,parts:[a[k],a[k+1]]});gain+=a[k].v*2;k++}else z.push(a[k])}for(let j=0;j<z.length;j++){let r=d=="L"||d=="R"?i:(d=="U"?j:3-j),c=d=="U"||d=="D"?i:(d=="L"?j:3-j),q=z[j];b[r][c]={v:q.v,id:q.id};for(let p of(q.parts||[q]))anim.push({id:p.id,r,c,target:q.v,merge:!!q.parts})}}if(JSON.stringify(b.map(x=>x.map(y=>y.v)))==JSON.stringify(s.b.map(x=>x.map(y=>y.v))))return null;n.b=b;n.score+=gain;n.moves++;return{n,anim}}
function pos(r,c){return`translate(calc(${c} * (100% + var(--gap))),calc(${r} * (100% + var(--gap))))`}
function renderBoard(){let L=$("#tiles");L.innerHTML="";for(let r=0;r<4;r++)for(let c=0;c<4;c++){let q=S.b[r][c];if(!q.v)continue;let e=document.createElement("div");e.dataset.id=q.id;e.className=`tile ${q.v>2048?"high":"v"+q.v}`;e.style.transform=pos(r,c);e.textContent=q.v;L.appendChild(e)}stats()}
function animate(q){let old=new Map([...$("#tiles").children].map(x=>[+x.dataset.id,x]));for(let m of q.anim){let e=old.get(m.id);if(!e)continue;if(m.merge){e.textContent=m.target;e.className=`tile ${m.target>2048?"high":"v"+m.target}`}e.style.transform=pos(m.r,m.c)}setTimeout(()=>{S=q.n;spawn(S);milestones();renderBoard();lock=0},135)}
function maxTile(){return Math.max(...S.b.flat().map(x=>x.v))}
function milestones(){let m=maxTile();for(let p=128;p<=m;p*=2)if(!S.marks[p]){let x={t:Date.now()-S.start,m:S.moves};S.marks[p]=x;CP[p]=clone(S);if(!REC.fastest[p]||x.t<REC.fastest[p])REC.fastest[p]=x.t;if(!REC.fewest[p]||x.m<REC.fewest[p])REC.fewest[p]=x.m;REC.bestTile=Math.max(REC.bestTile,p);save("cp",CP);save("records",REC)}}
function canMove(){return["L","R","U","D"].some(d=>move(S,d))}
function finishIfDead(){if(canMove())return;RUNS.unshift({date:Date.now(),score:S.score,tile:maxTile(),moves:S.moves,time:Date.now()-S.start,startTile:S.startTile,marks:S.marks});RUNS=RUNS.slice(0,50);save("runs",RUNS);setTimeout(()=>alert("Game Over – Run wurde gespeichert."),50)}
function go(d){if(lock)return;let q=move(S,d);if(!q){finishIfDead();return}lock=1;H.push(clone(S));if(H.length>200)H.shift();animate(q)}
window.undo=n=>{if(lock)return;while(n--&&H.length)S=H.pop();renderBoard()};window.newGame=()=>{if(S&&S.moves>0){RUNS.unshift({date:Date.now(),score:S.score,tile:maxTile(),moves:S.moves,time:Date.now()-S.start,startTile:S.startTile,marks:S.marks,aborted:true});RUNS=RUNS.slice(0,50);save("runs",RUNS)}S=fresh();H=[];renderBoard()}
function fmt(x){let s=x/1000|0,h=s/3600|0,m=(s%3600)/60|0,ss=s%60;return(h?h+":":"")+String(m).padStart(2,"0")+":"+String(ss).padStart(2,"0")}
function preview(){let mode=$("#preview").value;if(mode=="off")return"";if(mode=="value"){let q=clone(S.rng);return"Nächster Wert: "+(rnd(q)<.9?2:4)}let out=[],sy={L:"←",R:"→",U:"↑",D:"↓"};for(let d of["L","R","U","D"]){let z=move(S,d);if(!z)continue;let e=empty(z.n.b),q=clone(z.n.rng),p=e[Math.floor(rnd(q)*e.length)],v=rnd(q)<.9?2:4;out.push(`${sy[d]} ${v} @ ${String.fromCharCode(65+p[1])}${p[0]+1}`)}return out.join(" · ")}
function stats(){REC.bestScore=Math.max(REC.bestScore,S.score);REC.bestTile=Math.max(REC.bestTile,maxTile());save("records",REC);$("#score").textContent=S.score;$("#best").textContent=REC.bestScore;$("#moves").textContent=S.moves;$("#free").textContent=empty(S.b).length;let mx=maxTile(),g=128;while(g<=mx)g*=2;$("#goal").textContent=g;$("#next").textContent=preview();let a=Object.entries(S.marks);$("#marks").innerHTML=a.length?a.map(([k,v])=>`<div class=r><b>${k}</b><span>${fmt(v.t)} · Zug ${v.m}</span></div>`).join(""):"Noch keine.";let c=Object.keys(CP).map(Number).sort((a,b)=>a-b);$("#cps").innerHTML=c.length?c.map(k=>`<div class=r><b>${k}</b><button onclick=startCP(${k})>Ab hier</button></div>`).join(""):"Noch keine.";$("#records").innerHTML=`<div class=r><b>Höchste Kachel</b><span>${REC.bestTile||"-"}</span></div><div class=r><b>Höchster Score</b><span>${REC.bestScore}</span></div>`+Object.keys(REC.fastest).sort((a,b)=>a-b).map(k=>`<div class=r><b>${k}</b><span>Bestzeit ${fmt(REC.fastest[k])}<br><span class=muted>${REC.fewest[k]} Züge</span></span></div>`).join("");$("#runs").innerHTML=RUNS.length?RUNS.slice(0,12).map(r=>`<div class=r><b>${r.tile} · ${r.score}</b><span>${fmt(r.time)} · ${r.moves} Züge<br><span class=muted>${new Date(r.date).toLocaleDateString("de-DE")}${r.aborted?" · beendet":""}</span></span></div>`).join(""):"Noch keine abgeschlossenen Runs."}
window.startCP=k=>{S=clone(CP[k]);S.start=Date.now();S.startTile=+k;S.moves=0;S.score=0;S.marks={};H=[];renderBoard()};$("#preview").onchange=stats;$("#menu").onclick=()=>{$("#panel").classList.remove("hidden");stats()};$("#close").onclick=()=>$("#panel").classList.add("hidden");
for(let i=0;i<16;i++){let e=document.createElement("div");e.className="cell";$("#grid").appendChild(e)}let x,y,G=$("#game");G.ontouchstart=e=>{x=e.touches[0].clientX;y=e.touches[0].clientY};G.ontouchend=e=>{let X=e.changedTouches[0].clientX-x,Y=e.changedTouches[0].clientY-y;if(Math.max(Math.abs(X),Math.abs(Y))<22)return;go(Math.abs(X)>Math.abs(Y)?(X>0?"R":"L"):(Y>0?"D":"U"))};S=fresh();renderBoard();setInterval(()=>$("#time").textContent=fmt(Date.now()-S.start),1000);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");